Port: 8081

TotalStorage: 40000000

BarteringInitialScore: 10.0
BarteringFactorAcceptableRatio: 0.3
BarteringRatioIncreaseRate: 0.1


StoragerequestsScoreDecreaseRefusedStoReq: 0.8


StoragetestingTimerTimeoutSec: 5
StoragetestingTestingPeriod: 20
StoragetestingFailedTestTimeoutDecrease: 0.5
StoragetestingFailedTestWrongAnsDecrease: 0.7
StoragetestingPassedTestIncrease: 0.2

FailureModel : "weibull"
NodeProfile : "peer"
